services:
  nginx:
    build: nginx/
    links:
      - php-fpm
    ports:
      - 8080:80

  php-fpm:
    build: php-fpm/
    volumes:
      - .:/var/www/html
    links:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis
    ports:
      - 6379:6379

  phpunit:
    build: php-fpm/
    volumes:
      - .:/var/www/html
    links:
      - redis
      - nginx
    environment:
      - REDIS_HOST=redis
